apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: asd
            - name: POSTGRES_PASSWORD
              value: asd
            - name: POSTGRES_DB
              value: db
          volumeMounts:  # If using PVC for persistence
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
      volumes:  # If using PVC for persistence
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc

